### NumPy

In [6]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])

print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


### SciPy

In [7]:
from scipy import sparse

eye = np.eye(4)

print("Numpy Array:\n{}".format(eye))

sparse_matrix = sparse.csr_matrix(eye)

print("\nSciPy CSR sparse matrix:\n{}".format(sparse_matrix))

Numpy Array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

SciPy CSR sparse matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
